#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

source /data/venvs/smithers/bin/activate

# delete pyc files
find . -name "*.pyc" -delete

# make sure our dependencies are installed
bin/peep.py install -r requirements.txt
